### ISSUE TITLE
Code Cleanup -- FIXME and TODO

### ISSUE THREAD

**Issue by cycomachead** [beautyjoy/llab#31]
To Check off
- [ ] ./llab/css/default.css:/\* FIXME --- poorly performant. */
- [ ] ./llab/css/default.css:  border: 1px solid #888 !important; /\* FIXME */
- [ ] ./llab/css/default.css:/\* FIXME -- standardize class names! */
- [x] ./llab/css/default.css:/*\* FIXME -- replace this with bootstrap warning -- then delete
- [ ] ./llab/css/default.css:/\* FIXME, name needed */
- [ ] ./llab/css/default.css:/\* FIXME, name needed */
- [ ] ./llab/css/default.css:/\* FIXME, name needed */
- [ ] ./llab/css/default.css:/\* FIXME, name needed */
- [x] ./llab/css/default.css:  background-image: url(../img/slideshowIcon.png); /\* FIXME */
- [ ] ./llab/css/default.css:/*\* FIXME -- poorly performant, applies to all divs within */
- [x] ./llab/css/default.css:  background: url("../img/external-link.png") center right no-repeat; /\* FIXME */
- [x] ./llab/css/unused.css:    background-image:url(../img/sys/Alonzo-BYOB.jpg); FIXME
- [x] ./llab/css/unused.css:    background-image:url(../img/web/special-key-32.png); FIXME
- [x] ./llab/css/unused.css:/\* FIXME -- this is just bad */
- [ ] ./llab/loader.js:         (true) // FIXME -- proper bootstrap check
- [ ] ./llab/script/course.js:    // FIXME -- this is most surely buggy
- [ ] ./llab/script/curriculum.js: \*  FIXME: This should share code with llab.topic!
- [ ] ./llab/script/curriculum.js:    // FIXME -- will break on pages with multiple dropdowns (future)
- [ ] ./llab/script/curriculum.js:    // FIXME -- shouldn't special case this
- [ ] ./llab/script/curriculum.js:        // FIXME this needs to be a selector
- [ ] ./llab/script/curriculum.js:    // FIXME -- Not great on widnow resize
- [ ] ./llab/script/curriculum.js:    // FIXME -- clean up!!
- [x] ./llab/script/curriculum.js:    // FIXME -- this requires a step as a URL param currently.
- [ ] ./llab/script/library.js:    // FIXME -- This is most surely buggy
- [x] ./llab/script/library.js:// FIXME -- this should be wrapped in some proper call
- [ ] ./llab/script/topic.js:// FIXME -- documentation needed.
- [ ] ./llab/script/topic.js:    // FIXME -- refactor check
- [x] ./topic/berkeley_bjc/python/besides-blocks-intro.topic:// learning-goal: FIXME
- [x] ./topic/berkeley_bjc/python/besides-blocks-intro.topic:// learning-goal: FIXME
- [x] ./topic/berkeley_bjc/python/besides-blocks-intro.topic:// learning-goal: FIXME
- [x] ./cur/programming/loops/repeat-n/draw-regular-polygons-with-repeat.html:        <!-- TODO
- [x] ./llab/config.js:llab.paths.css_files.push("css/from-mvle.css"); // TODO lose this one please
- [ ] ./llab/css/default.css:/\* TODO: Create a real .list-bg class */
- [ ] ./llab/doc/example.quiz:(TODO)
- [ ] ./llab/script/curriculum.js: // TODO: These need to be moved to a better place:
- [ ] ./llab/script/curriculum.js: // TODO clean this up
- [x] ./llab/script/curriculum.js: // TODO -- this shouldn't happen, but we could intelligently find 
- [ ] ./llab/script/curriculum.js: // TODO:  Check if we have a title for this link?
- [ ] ./llab/script/curriculum.js: //TODO: Does this matter?
- [ ] ./llab/script/curriculum.js: // TODO -- set the mobile viewport, but the display needs to look right
- [x] ./llab/script/curriculum.js: // TODO -- cleanup use selectors for classes
- [ ] ./llab/script/curriculum.js: // TODO REFACTOR THIS
- [ ] ./llab/script/curriculum.js: // TODO: Update page content and push URL onto browser back button
- [ ] ./llab/script/curriculum.js: // TODO: Make this config
- [ ] ./llab/script/glossary.js: // TODO term wasn't there
- [ ] ./llab/script/glossary.js: // TODO server didn't send index back, yo
- [ ] ./llab/script/library.js: // TODO: Move to config potentially
- [ ] ./llab/script/library.js: // // TODO: Move this to config? Or refactor?
- [x] ./llab/script/library.js: //TODO put this in the llab namespace
- [x] ./llab/script/library.js: // TODO: Shorten string to end on whole words?
- [ ] ./llab/script/library.js: // TODO: Be smarter about stripping from HTML content
- [x] ./llab/script/quiz/multiplechoice.js: // TODO -- what are these doing?  need to move from id's to classes eventually...
- [ ] ./llab/script/quiz/multiplechoice.js: // should this be here??? TODO
- [x] ./llab/script/topic.js: //TODO pull out the html tags for the page title
- [ ] ./llab/script/topic.js: // TODO -- better error messge.  maybe show default course or topic?
- [x] ./topic/berkeley_bjc/apps/applications-that-changed-the-world.topic: //TODO   resource: Searching in <span class="snap">snap</span> [/bjc-r/cur/programming/hash-tables/searching-in-snap.html]
- [x] ./topic/berkeley_bjc/intro_new/2-loops-variables.topic: //quiz: TODO Test Yourself: FOR [/bjc-r/cur/programming/loops/for/test-yourself-for.html]
- [x] ./topic/berkeley_bjc/intro_new/2-loops-variables.topic: //resource: TODO motivation...  (we had it before w/ broadcast/wait...  how can we motivate it now? square?)
- [x] ./topic/berkeley_bjc/intro_new/2-loops-variables.topic: //resource: TODO a list of simple blocks to make, to practice on.  draw-triangle(size), etc 
- [x] ./topic/berkeley_bjc/intro_new/2-loops-variables.topic: //quiz: TODO practice  composing functions (1/2 of Jessica's previous quiz?)
- [x] ./topic/original_bjc/16-applications-that-changed-the-world.topic: //TODO resource: Searching in <span class="snap">snap</span> [/bjc-r/cur/programming/hash-tables/searching-in-snap.html]

There's a few TODO which belong in bjc-r. I'll create that issue later.
